version: '3'
services:

  mysql:
    image: "mariadb:latest"
    ports:
      - "${DB_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD:-super.secret.123}"
      MYSQL_USER: "${DB_USER:-websocketserver}"
      MYSQL_PASSWORD: "${DB_PASSWORD:-wspassword}"
      MYSQL_DATABASE: "${DB_NAME:-websocketserver}"
